export type PodStatus = "Running" | "Pending" | "Failed" | "Succeeded";

export type PodOwner = {
  kind: "ReplicaSet" | "StatefulSet" | "DaemonSet" | "Job" | "CronJob";
  name: string;
};

export type PodRecord = {
  name: string;
  namespace: string;
  status: PodStatus;
  ready: string;
  restarts: number;
  age: string;
  image: string;
  owner: PodOwner;
  memory: string;
  cpu: string;
  created: string;
};

export const PODS: PodRecord[] = [
  {
    name: "nginx-deployment-7d8c9f6b-4xk2p",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "12d",
    image: "nginx:1.21",
    owner: { kind: "ReplicaSet", name: "nginx-deployment-7d8c9f6b" },
    memory: "12.4 MiB",
    cpu: "0.002 cores",
    created: "May 14, 2026, 9:18 AM",
  },
  {
    name: "nginx-deployment-7d8c9f6b-mx8qz",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 2,
    age: "12d",
    image: "nginx:1.21",
    owner: { kind: "ReplicaSet", name: "nginx-deployment-7d8c9f6b" },
    memory: "11.8 MiB",
    cpu: "0.001 cores",
    created: "May 14, 2026, 9:18 AM",
  },
  {
    name: "nginx-deployment-7d8c9f6b-n5p9r",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "12d",
    image: "nginx:1.21",
    owner: { kind: "ReplicaSet", name: "nginx-deployment-7d8c9f6b" },
    memory: "12.1 MiB",
    cpu: "0.002 cores",
    created: "May 14, 2026, 9:19 AM",
  },
  {
    name: "redis-master-0",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 1,
    age: "45d",
    image: "redis:7.0",
    owner: { kind: "StatefulSet", name: "redis-master" },
    memory: "48.2 MiB",
    cpu: "0.012 cores",
    created: "Apr 11, 2026, 2:04 PM",
  },
  {
    name: "postgres-statefulset-0",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "89d",
    image: "postgres:14",
    owner: { kind: "StatefulSet", name: "postgres-statefulset" },
    memory: "256.4 MiB",
    cpu: "0.045 cores",
    created: "Feb 26, 2026, 8:30 AM",
  },
  {
    name: "postgres-statefulset-1",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "89d",
    image: "postgres:14",
    owner: { kind: "StatefulSet", name: "postgres-statefulset" },
    memory: "248.9 MiB",
    cpu: "0.041 cores",
    created: "Feb 26, 2026, 8:31 AM",
  },
  {
    name: "elasticsearch-data-0",
    namespace: "logging",
    status: "Running",
    ready: "1/1",
    restarts: 3,
    age: "156d",
    image: "elasticsearch:8.5",
    owner: { kind: "StatefulSet", name: "elasticsearch-data" },
    memory: "1.2 GiB",
    cpu: "0.320 cores",
    created: "Dec 21, 2025, 11:02 AM",
  },
  {
    name: "elasticsearch-data-1",
    namespace: "logging",
    status: "Running",
    ready: "1/1",
    restarts: 2,
    age: "156d",
    image: "elasticsearch:8.5",
    owner: { kind: "StatefulSet", name: "elasticsearch-data" },
    memory: "1.1 GiB",
    cpu: "0.298 cores",
    created: "Dec 21, 2025, 11:03 AM",
  },
  {
    name: "fluentd-daemonset-7g8h2",
    namespace: "logging",
    status: "Running",
    ready: "1/1",
    restarts: 5,
    age: "156d",
    image: "fluentd:v1.14",
    owner: { kind: "DaemonSet", name: "fluentd-daemonset" },
    memory: "86.4 MiB",
    cpu: "0.018 cores",
    created: "Dec 21, 2025, 11:05 AM",
  },
  {
    name: "fluentd-daemonset-k9m3n",
    namespace: "logging",
    status: "Running",
    ready: "1/1",
    restarts: 4,
    age: "156d",
    image: "fluentd:v1.14",
    owner: { kind: "DaemonSet", name: "fluentd-daemonset" },
    memory: "84.1 MiB",
    cpu: "0.016 cores",
    created: "Dec 21, 2025, 11:05 AM",
  },
  {
    name: "fluentd-daemonset-p2r5t",
    namespace: "logging",
    status: "Running",
    ready: "1/1",
    restarts: 6,
    age: "156d",
    image: "fluentd:v1.14",
    owner: { kind: "DaemonSet", name: "fluentd-daemonset" },
    memory: "85.0 MiB",
    cpu: "0.017 cores",
    created: "Dec 21, 2025, 11:06 AM",
  },
  {
    name: "prometheus-server-0",
    namespace: "monitoring",
    status: "Running",
    ready: "1/1",
    restarts: 1,
    age: "67d",
    image: "prometheus:v2.40",
    owner: { kind: "StatefulSet", name: "prometheus-server" },
    memory: "512.8 MiB",
    cpu: "0.180 cores",
    created: "Mar 20, 2026, 4:22 PM",
  },
  {
    name: "grafana-deployment-6f8d9c-x4k8p",
    namespace: "monitoring",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "23d",
    image: "grafana:9.3",
    owner: { kind: "ReplicaSet", name: "grafana-deployment-6f8d9c" },
    memory: "96.2 MiB",
    cpu: "0.024 cores",
    created: "May 3, 2026, 10:15 AM",
  },
  {
    name: "alertmanager-0",
    namespace: "monitoring",
    status: "Running",
    ready: "1/1",
    restarts: 2,
    age: "67d",
    image: "alertmanager:v0.25",
    owner: { kind: "StatefulSet", name: "alertmanager" },
    memory: "32.6 MiB",
    cpu: "0.008 cores",
    created: "Mar 20, 2026, 4:25 PM",
  },
  {
    name: "api-gateway-7c9d8f-5n6p7",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "8d",
    image: "api-gateway:v2.1",
    owner: { kind: "ReplicaSet", name: "api-gateway-7c9d8f" },
    memory: "64.0 MiB",
    cpu: "0.015 cores",
    created: "May 18, 2026, 1:42 PM",
  },
  {
    name: "api-gateway-7c9d8f-8q9r2",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 1,
    age: "8d",
    image: "api-gateway:v2.1",
    owner: { kind: "ReplicaSet", name: "api-gateway-7c9d8f" },
    memory: "63.4 MiB",
    cpu: "0.014 cores",
    created: "May 18, 2026, 1:42 PM",
  },
  {
    name: "auth-service-5b6c7d-3m4n5",
    namespace: "production",
    status: "Running",
    ready: "1/1",
    restarts: 0,
    age: "15d",
    image: "auth-service:v1.8",
    owner: { kind: "ReplicaSet", name: "auth-service-5b6c7d" },
    memory: "72.8 MiB",
    cpu: "0.019 cores",
    created: "May 11, 2026, 8:00 AM",
  },
  {
    name: "backup-job-1710720000",
    namespace: "production",
    status: "Succeeded",
    ready: "0/1",
    restarts: 0,
    age: "2d",
    image: "backup:latest",
    owner: { kind: "Job", name: "backup-job" },
    memory: "—",
    cpu: "—",
    created: "May 24, 2026, 6:00 AM",
  },
  {
    name: "database-migration-job",
    namespace: "production",
    status: "Succeeded",
    ready: "0/1",
    restarts: 0,
    age: "5d",
    image: "migration:v1.2",
    owner: { kind: "Job", name: "database-migration" },
    memory: "—",
    cpu: "—",
    created: "May 21, 2026, 3:30 PM",
  },
  {
    name: "test-runner-7h8i9j",
    namespace: "development",
    status: "Pending",
    ready: "0/1",
    restarts: 0,
    age: "5m",
    image: "test-runner:latest",
    owner: { kind: "ReplicaSet", name: "test-runner-7h8i9j" },
    memory: "—",
    cpu: "—",
    created: "May 26, 2026, 1:05 PM",
  },
  {
    name: "cache-cleanup-job-failed",
    namespace: "production",
    status: "Failed",
    ready: "0/1",
    restarts: 3,
    age: "1h",
    image: "cache-cleanup:v1.0",
    owner: { kind: "Job", name: "cache-cleanup" },
    memory: "—",
    cpu: "—",
    created: "May 26, 2026, 12:10 PM",
  },
];

export const podDetailPath = (namespace: string, name: string) =>
  `/workloads/pods/${encodeURIComponent(namespace)}/${encodeURIComponent(name)}`;

export const getPodByKey = (namespace: string, name: string): PodRecord | undefined =>
  PODS.find((p) => p.namespace === namespace && p.name === name);
